sys:
  cpus: 3

data:
  input: '/var/local/robo-music-data/brian-eno-ambient-1-cut'
  cache: './cache'
  logs: './logs'

audio:
  sample_rate: 11025
  channels: 1

classifier:
  n_mels: 128

synth:
  sample_augmentation: 8
  augmentation_noise: 0.02
  augmentation_scale_range: 1.2
  feature_window: 2048
  slice_size: 25000
  quantisation: 256
  batch_size: 6
  steps: 10000
  steps_per_eval: 500
  eval_steps: 100
  conditioning: false
  regularisation: false
  dropout: false
  dilation_stack_depth: 8
  dilation_stack_count: 5
  conv_filters: 32
  residual_filters: 32
  skip_filters: 64
  validation_file: '/var/local/robo-music-data/brian-eno-ambient-1-cut/music/Brian Eno - Ambient 1- Music for Airports [Full Album].mp3'
