sys:
  cpus: 3

data:
  input: './data'
  cache: './cache'
  logs: './logs'

audio:
  sample_rate: 11025
  channels: 1

classifier:
  n_mels: 128

synth:
  sample_augmentation: 4
  augmentation_noise: 0.02
  augmentation_scale_range: 1.2
  feature_window: 2048
  slice_size: 25000
  quantisation: 256
  prepare_batch_size: 100000
  batch_size: 2
  steps: 50000
  steps_per_eval: 5000
  eval_steps: 100
  conditioning: false
  regularisation: 0.0
  dropout: false
  dilation_stack_depth: 10
  dilation_stack_count: 6
  conv_filters: 64
  residual_filters: 64
  skip_filters: 128
  validation_file: './data/music/sample1.wav'
