data:
  input: './data'
  cache: './cache'
  logs: './logs'

audio:
  sample_rate: 11025
  channels: 1

classifier:
  n_mels: 128

synth:
  slice_size: 2048
  quantisation: 256
  batch_size: 100
  epoch_count: 1
