#!/usr/bin/env python
import pickle
import re
import sys
from collections import Counter


def main(argv):
    in_path = argv[1]
    pattern_str = argv[3]
    with open(in_path, 'rb') as file:
        allocation_list = pickle.load(file)

    pattern = re.compile(pattern_str)
    count(pattern, allocation_list)


def count(pattern, allocation_list):
    matches = Counter()
    total = 0

    for allocation in allocation_list:
        time, size, tensor = allocation
        if pattern.match(tensor):
            matches[tensor] += size
            total += size

    for size, tensor in sorted((v, k) for k, v in matches.items()):
        print(f'{size}: {tensor}')
        print(f'total: {total}')


if __name__ == '__main__':
    main(sys.argv)
