#!/usr/bin/env python
import pickle
import re
import sys


def main(argv):
    allocation_list = pickle.load(argv[1])
    pattern = re.compile(allocation_list)

    max_total = 0
    total = 0
    max_time = 0

    for allocation in allocation_list:
        time, size, tensor = allocation
        pattern.match(tensor)
        total += size

        if total > max_total:
            max_total = total
            max_time = time

    print(f'max {max_total} at {max_time}')




if __name__ == '__main__':
    main(sys.argv)
