#!/usr/bin/env python

import re
import sys
import os
import subprocess
from collections import Counter, defaultdict

allocation_re = re.compile(br'(de)?allocated (\d+) for tensor (.+)')


def main(argv):
    proc = start_proc(argv[1:])
    allocations = debug_process(proc)
    print_stats(allocations)


def start_proc(args):
    environ = os.environ.copy()
    environ['PYTHONUNBUFFERED'] = '1'
    environ['TF_CPP_MIN_VLOG_LEVEL'] = '3'

    return subprocess.Popen(args, env=environ, stderr=subprocess.PIPE)


def debug_process(proc):
    allocations = Counter()
    max_allocations = defaultdict(int)
    total_allocation = 0
    max_total_allocation = 0
    for line in proc.stderr:
        match = allocation_re.search(line)
        if not match:
            continue
        print(line)

        deallocation, size, tensor = match.groups()
        size = int(size)
        if deallocation:
            size = -size
        allocations[tensor] += size
        max_allocations[tensor] = max(
            allocations[tensor], max_allocations[tensor]
        )

        total_allocation += size
        max_total_allocation = max(total_allocation, max_total_allocation)

    return list((v, k) for k, v in allocations.items())


def print_stats(allocations):
    top = sorted(allocations, reverse=True)[:100]
    for size, tensor in top:
        print(f'{size} - {tensor}')


if __name__ == '__main__':
    main(sys.argv)
